application: picture-map
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /static
  static_dir: app/static
  secure: always

- url: /admin.*
  script: app.main.admin
  login: admin
  secure: always

- url: .*
  script: app.main.app
  secure: always

libraries:
- name: webapp2
  version: "2.5.2"

- name: webob
  version: latest

- name: jinja2
  version: latest
